### ISSUE TITLE
你好，有对应的告警指标可供参考不？

### ISSUE THREAD

**Issue by imlxh** [woozhijun/flume_exporter#1]
你好，感谢分享flume exporter监控组件，有对应的告警指标可供参考不？还有grafana图表有对应的能分享下不，非常感谢

**Comment by woozhijun** [comment]
Ok. 
Please refer to https://grafana.com/grafana/dashboards/10736 
This is work.

**Comment by woozhijun** [comment]
> 你好，感谢分享flume exporter监控组件，有对应的告警指标可供参考不？还有grafana图表有对应的能分享下不，非常感谢

Ok.
Please refer to https://grafana.com/grafana/dashboards/10736
This is work.

**Comment by imlxh** [comment]
好的，非常感谢
