### ISSUE TITLE
如何在goland中编译

### ISSUE THREAD

**Issue by zhihui-ge** [woozhijun/flume_exporter#3]
gopath  
![image](https://user-images.githubusercontent.com/17016370/64661213-63605d80-d476-11e9-89f8-ac25b07430b6.png)

H:\workspace-go\flume_exporter>go build
flume_exporter.go:4:2: cannot find package "github.com/Sirupsen/logrus" in any of:
        H:\develop\Go\src\github.com\Sirupsen\logrus (from $GOROOT)
        H:\workspace-go\flume_exporter\src\github.com\Sirupsen\logrus (from $GOPATH)
        H:\workspace-go\flume_exporter\vendor\src\github.com\Sirupsen\logrus
        H:\workspace-go\src\github.com\Sirupsen\logrus
flume_exporter.go:5:2: cannot find package "github.com/prometheus/client_golang/prometheus" in any of:
        H:\develop\Go\src\github.com\prometheus\client_golang\prometheus (from $GOROOT)
        H:\workspace-go\flume_exporter\src\github.com\prometheus\client_golang\prometheus (from $GOPATH)
        H:\workspace-go\flume_exporter\vendor\src\github.com\prometheus\client_golang\prometheus
        H:\workspace-go\src\github.com\prometheus\client_golang\prometheus
flume_exporter.go:6:2: cannot find package "github.com/prometheus/client_golang/prometheus/promhttp" in any of:
        H:\develop\Go\src\github.com\prometheus\client_golang\prometheus\promhttp (from $GOROOT)
        H:\workspace-go\flume_exporter\src\github.com\prometheus\client_golang\prometheus\promhttp (from $GOPATH)
        H:\workspace-go\flume_exporter\vendor\src\github.com\prometheus\client_golang\prometheus\promhttp
        H:\workspace-go\src\github.com\prometheus\client_golang\prometheus\promhttp
flume_exporter.go:7:2: cannot find package "github.com/prometheus/common/version" in any of:
        H:\develop\Go\src\github.com\prometheus\common\version (from $GOROOT)
        H:\workspace-go\flume_exporter\src\github.com\prometheus\common\version (from $GOPATH)
        H:\workspace-go\flume_exporter\vendor\src\github.com\prometheus\common\version
        H:\workspace-go\src\github.com\prometheus\common\version
flume_exporter.go:8:2: cannot find package "github.com/woozhijun/flume_exporter/exporter" in any of:
        H:\develop\Go\src\github.com\woozhijun\flume_exporter\exporter (from $GOROOT)
        H:\workspace-go\flume_exporter\src\github.com\woozhijun\flume_exporter\exporter (from $GOPATH)
        H:\workspace-go\flume_exporter\vendor\src\github.com\woozhijun\flume_exporter\exporter
        H:\workspace-go\src\github.com\woozhijun\flume_exporter\exporter
flume_exporter.go:9:2: cannot find package "gopkg.in/alecthomas/kingpin.v2" in any of:
        H:\develop\Go\src\gopkg.in\alecthomas\kingpin.v2 (from $GOROOT)
        H:\workspace-go\flume_exporter\src\gopkg.in\alecthomas\kingpin.v2 (from $GOPATH)
        H:\workspace-go\flume_exporter\vendor\src\gopkg.in\alecthomas\kingpin.v2
        H:\workspace-go\src\gopkg.in\alecthomas\kingpin.v2

**Comment by woozhijun** [comment]
@zhihui-ge 
Check Gopath/Goroot 
> go env

then,

> mkdir -p $GOPATH/src/github.com/woozhijun
> git clone -b master https://github.com/woozhijun/flume_exporter.git
> make build

**Comment by zhihui-ge** [comment]
是在window环境使用GoLand进行编译，可以使用go get github.com/xxxxx/xxxx解决，会在项目下面生成src目录，然后可以编译成功的
![image](https://user-images.githubusercontent.com/17016370/64663407-3e6fe880-d47e-11e9-8131-f89be7cda420.png)
