### ISSUE TITLE
make build error  Makefile:27: recipe for target 'build' failed make: *** [build] Error 1

### ISSUE THREAD

**Issue by zhengkw** [woozhijun/flume_exporter#7]
>   flume_exporter
go: github.com/woozhijun/flume_exporter imports
	github.com/Sirupsen/logrus: github.com/Sirupsen/logrus@v1.7.0: parsing go.mod:
	module declares its path as: github.com/sirupsen/logrus
	        but was required as: github.com/Sirupsen/logrus
!! command failed: build -o /home/impdatahd/go/src/github.com/woozhijun/flume_exporter/flume_exporter -ldflags -X github.com/prometheus/common/version.Version=0.0.2 -X github.com/prometheus/common/version.Revision=c07a0546e273185a67b0262541f1c57d09da60d5 -X github.com/prometheus/common/version.Branch=master -X github.com/prometheus/common/version.BuildUser=impdatahd@yxhddata04 -X github.com/prometheus/common/version.BuildDate=20210119-09:45:49  -extldflags '-static' -a -tags netgo github.com/woozhijun/flume_exporter: exit status 1
Makefile:27: recipe for target 'build' failed
make: *** [build] Error 1

---------------------------------------------------

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/impdatahd/.cache/go-build"
GOENV="/home/impdatahd/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/impdatahd/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build991322613=/tmp/go-build -gno-record-gcc-switches"
---------------------------------------------
source path：
/home/impdatahd/go/src/github.com/woozhijun/flume_exporter

**Comment by zhengkw** [comment]
go version go1.13.4 linux/amd64

**Comment by zhengkw** [comment]
must be use root????

**Comment by zhengkw** [comment]
use root????

**Comment by woozhijun** [comment]
I just updated go version for 1.13, and add go module, remove dep vendor.
You are try ?  @zhengkw

**Comment by zhengkw** [comment]
using the root account solved the problem
